In [ ]:
import torch
import torch.nn as nn

# Convolution Layer 정의
conv_layer = nn.Conv2d(
    in_channels=1, # 입력 채널 (단일 채널 흑백 이미지)
    out_channels=1, # 출력 채널 (필터 개수 1개)
    kernel_size=3, # 필터 크기 (3x3)
    stride=1, # 필터 이동 간격
    padding=0 # 패딩 없음
)

# Convolution Layer의 가중치를 수동으로 설정
with torch.no_grad(): # 가중치 수동 설정 시 기울기 추적 방지
    conv_layer.weight = nn.Parameter(torch.tensor([[[[2, 0, 1],
                                                     [0, 1, 2],
                                                     [1, 0, 2]]]],
                                                     dtype=torch.float32)) # 3x3 필터
    conv_layer.bias = nn.Parameter(torch.tensor([0], dtype=torch.float32)) # 바이어스 0으로 설정

# 입력 데이터 생성 (변수: input_data, 크기: 1x1x5x5)
input_data = torch.tensor([[[[1, 2, 3, 0],
                             [0, 1, 2, 3],
                             [3, 0, 1, 2],
                             [2, 3, 0, 1]]]], dtype=torch.float32)

# Convolution Layer 출력
output_data = conv_layer(input_data)

# 결과 출력
print("입력 데이터:")
print(input_data)

print("\n가중치 (Weights):")
print(conv_layer.weight)

print("\n바이어스 (Bias):")
print(conv_layer.bias)

print("\n출력 데이터:")
print(output_data)

입력 데이터:
tensor([[[[1., 2., 3., 0.],
          [0., 1., 2., 3.],
          [3., 0., 1., 2.],
          [2., 3., 0., 1.]]]])

가중치 (Weights):
Parameter containing:
tensor([[[[2., 0., 1.],
          [0., 1., 2.],
          [1., 0., 2.]]]], requires_grad=True)

바이어스 (Bias):
Parameter containing:
tensor([0.], requires_grad=True)

출력 데이터:
tensor([[[[15., 16.],
          [ 6., 15.]]]], grad_fn=<ConvolutionBackward0>)
