In [ ]:
import torch
import torch.nn as nn

# Linear layer 정의 (입력 5개, 출력 1개)
linear_layer = nn.Linear(in_features=5, out_features=1)

# 가중치와 바이어스를 수동으로 설정
with torch.no_grad(): # 가중치 수동 설정 시 기울기 추적 방지
    linear_layer.weight = nn.Parameter(torch.tensor([[1, 2, 3, 4, 5]],
                                                    dtype=torch.float32)) # 가중치 (1x5)
    linear_layer.bias = nn.Parameter(torch.tensor([1],
                                                  dtype=torch.float32)) # 바이어스 (1)

# 입력 데이터 생성 (변수: input_data, 크기: 1x5)
input_data = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.float32) # 크기: 1x5

# Linear layer 출력
output = linear_layer(input_data)

# 결과 출력
print("입력 데이터:")
print(input_data)

print("\n가중치 (Weights):")
print(linear_layer.weight)

print("\n바이어스 (Bias):")
print(linear_layer.bias)

print("\n출력 데이터:")
print(output)

입력 데이터:
tensor([[1., 2., 3., 4., 5.]])

가중치 (Weights):
Parameter containing:
tensor([[1., 2., 3., 4., 5.]], requires_grad=True)

바이어스 (Bias):
Parameter containing:
tensor([1.], requires_grad=True)

출력 데이터:
tensor([[56.]], grad_fn=<AddmmBackward0>)
